### ISSUE TITLE
The reset vector is read in reverse order

### ISSUE THREAD

**Issue by omarandlorraine** [gianlucag/mos6502#14]
A real chip, and Mike Chambers' fake6502 as well, read the reset vector low byte first (i.e. $fffc) and then $fffd. But it seems like this emulator does it in reverse order.

I appreciate it's a tiny thing but it's showing as a difference in [my test suite](https://github.com/omarandlorraine/solid65)

What do we think? Do we care about such tiny differences?

**Comment by omarandlorraine** [comment]
Looks like the locus of the bug is line 826 of mos6502.cpp. But also, I dont know if C++ actually defines the order in which those reads happen. Can anyone shed any light on this?

**Comment by gianlucag** [comment]
Could you please fork the project and submit a pull request?
