### ISSUE TITLE
Misleading README suggests that Commodore 64 used, 6502.

### ISSUE THREAD

**Issue by kaitabuchi314** [gianlucag/mos6502#21]
The README suggests the C64 used the 6502, but actually, it used the 6510, is this a 6502 emulation or 6510? It suggests you could make a C64 with this emulation, but if it is a 6502 emulator, it may or may not work.

**Comment by kaitabuchi314** [comment]
Can this be used to make a C64 emulator/simulator/what ever you call that? If not, the Commodore 64 part should probably be removed.

**Comment by gianlucag** [comment]
> Can this be used to make a C64 emulator/simulator/what ever you call that? If not, the Commodore 64 part should probably be removed. This is because someone may think that they can!

It can be totally used to make a C64 emulator. Three-state pins and the extra 6 bit I/O port would be coded outside the cpu emulator itself. The three state thing is a synchronization problem, while the 6 bit I/O port is encoded in the address decoding login of the emulator.
