### ISSUE TITLE
Not an issue,asking about usage?

### ISSUE THREAD

**Issue by Last-Hub-vode** [gianlucag/mos6502#25]

**Comment by Jimsoft1** [comment]
Same, have you got an example of how to use this code?  I can't get this to work!

**Comment by gianlucag** [comment]
> Same, have you got an example of how to use this code? I can't get this to work!

Please have a look at my other project (SidBerry SID emulator), which uses the mos6502 emulator

**Comment by Last-Hub-vode** [comment]
I found out.
